[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[headers]]
for = "/_next/static/*"

  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/_next/image"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200

  [redirects.query]
  url = ":url"
  w = ":width"
  q = ":quality"

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200

  [redirects.query]
  url = ":url"
  w = ":width"
  q = ":quality"

[context]

  [context.deploy-preview]

    [[context.deploy-preview.headers]]
    for = "/_next/static/*"

      [context.deploy-preview.headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

  [context."feat/nextjs-supabase-app"]

    [[context."feat/nextjs-supabase-app".headers]]
    for = "/_next/static/*"

      [context."feat/nextjs-supabase-app".headers.values]
      Cache-Control = "public, max-age=31536000, immutable"